[package]
name = "condvar_sync"
version = "0.1.0"
authors = ["Ebuka Agbanyim <ebuka7@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
